name ='sahil deo oron' #string(str)
age = 19 #integer(int)
cgpa = 7.7 #floats(float)
print(name)
print(age)
print(cgpa)
print(type(name))
print(type(age))
print(type(cgpa))
print(int(cgpa))
print(float(age))
name = (input('what is your name'))
age=(input('what is your age'))
cgpa=(input('what is your cgpa'))
a=int((input('what is your profit')))
b=int((input('what was the cost price')))
selling_price = (a+b)
print(selling_price)